In [72]:
import os
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn import preprocessing

In [73]:
print(os.getcwd())

/home/gca21/master/data-engineering/Proyecto-Ingenieria-Dato/Notebooks

In [74]:
PATH = os.getcwd() + "/../src/data/HU4_EDA.csv"
df = pd.read_csv(PATH)

In [75]:
df.head(15)

,nombre,pactivos,labtitular,labcomercializador,dosis (mg),forma_farmaceutica_simplificada,estado_aut,estado_rev,vias_administracion,comercializado,generico,afecta_conduccion,num_principios_activos,Volumen_Informativo,Complejidad_Desglose,Indicador_Riesgo,Estado,Precio venta al público con IVA,Tratamiento de larga duración
0,"ALMOTRIPTAN CINFA 12,5 MG COMPRIMIDOS RECUBIER...",ALMOTRIPTAN,Laboratorios Cinfa S.A.,Laboratorios Cinfa S.A.,12.5,COMPRIMIDO,2014-04-16 12:43:40,2014-04-16 12:43:40,VÍA ORAL,1,1,1,1,636,1,14,ALTA,32.085076,NO
1,"ALMOTRIPTAN NORMON 12,5 MG COMPRIMIDOS RECUBIE...",ALMOTRIPTAN,Laboratorios Normon S.A.,Laboratorios Normon S.A.,12.5,COMPRIMIDO,2013-06-18 06:25:10,2013-06-18 06:25:10,VÍA ORAL,1,1,1,1,662,1,13,ALTA,19.530000,NO
2,"ALMOTRIPTAN STADA 12,5 MG COMPRIMIDOS RECUBIER...",ALMOTRIPTAN,Laboratorio Stada S.L.,Laboratorio Stada S.L.,12.5,COMPRIMIDO,2014-01-26 23:00:00,2014-01-26 23:00:00,VÍA ORAL,1,1,1,1,650,1,13,ALTA,19.530000,NO
3,IBUPROFENO (ARGININA) KERN PHARMA 600 mg GRANU...,IBUPROFENO,Kern Pharma S.L.,Kern Pharma S.L.,600.0,SOLUCIÓN,2008-01-29 23:00:00,2008-01-29 23:00:00,VÍA ORAL,1,1,0,1,1375,0,12,BAJA POR NO COMERCIALIZAR,2.500000,NO
4,IBUPROFENO STADA 600 MG COMPRIMIDOS RECUBIERTO...,IBUPROFENO,Laboratorio Stada S.L.,Laboratorio Stada S.L.,600.0,COMPRIMIDO,2013-06-10 22:00:00,2013-06-10 22:00:00,VÍA ORAL,1,1,0,1,1238,0,13,ALTA,1.970000,NO
5,IMIGRAN 20 mg SOLUCION PARA PULVERIZACION NASAL.,SUMATRIPTAN,Glaxosmithkline S.A.,Glaxosmithkline S.A.,20.0,PRODUCTO USO NASAL,1998-03-31 22:00:00,1998-03-31 22:00:00,VÍA NASAL,1,0,1,1,543,0,5,ALTA,21.400000,NO
6,"NARAMIG 2,5 mg COMPRIMIDOS RECUBIERTOS CON PEL...",NARATRIPTAN HIDROCLORURO,Glaxo S.A.,Glaxo S.A.,2.5,COMPRIMIDO,1998-06-30 22:00:00,1998-06-30 22:00:00,VÍA ORAL,1,0,1,1,510,1,5,ALTA,12.461851,NO
7,RELERT 20 mg COMPRIMIDOS RECUBIERTOS CON PELICULA,ELETRIPTAN HIDROBROMURO,Viatris Healthcare Limited,Viatris Pharmaceuticals S.L.U.,20.0,COMPRIMIDO,2001-07-25 22:00:00,2001-07-25 22:00:00,VÍA ORAL,1,0,1,1,657,6,12,ALTA,8.800000,NO
8,RELERT 40 mg COMPRIMIDOS RECUBIERTOS CON PELICULA,ELETRIPTAN HIDROBROMURO,Viatris Healthcare Limited,Viatris Pharmaceuticals S.L.U.,40.0,COMPRIMIDO,2001-07-25 22:00:00,2001-07-25 22:00:00,VÍA ORAL,1,0,1,1,657,6,12,ALTA,17.590000,NO
9,RELPAX 20 mg COMPRIMIDOS RECUBIERTOS CON PELICULA,ELETRIPTAN HIDROBROMURO,Viatris Healthcare Limited,Viatris Pharmaceuticals S.L.U.,20.0,COMPRIMIDO,2001-07-25 22:00:00,2001-07-25 22:00:00,VÍA ORAL,1,0,1,1,657,1,12,ALTA,8.800000,NO
10,RELPAX 40 mg COMPRIMIDOS RECUBIERTOS CON PELICULA,ELETRIPTAN HIDROBROMURO,Viatris Healthcare Limited,Viatris Pharmaceuticals S.L.U.,40.0,COMPRIMIDO,2001-07-25 22:00:00,2001-07-25 22:00:00,VÍA ORAL,1,0,1,1,657,1,12,ALTA,17.590000,NO
11,RIZATRIPTAN VISO FARMACEUTICA 10 MG COMPRIMIDO...,RIZATRIPTAN BENZOATO,Glenmark Arzneimittel Gmbh,Glenmark Farmaceutica S.L.U,10.0,COMPRIMIDO BUCODISPERSABLE,2014-01-15 23:00:00,2014-01-15 23:00:00,VÍA ORAL,1,1,1,1,684,0,10,ALTA,8.800000,NO
12,RIZATRIPTAN VISO FARMACÉUTICA 10 MG COMPRIMIDO...,RIZATRIPTAN BENZOATO,Glenmark Arzneimittel Gmbh,Glenmark Farmaceutica S.L.U,10.0,COMPRIMIDO,2013-05-12 22:00:00,2013-05-12 22:00:00,VÍA ORAL,1,1,1,1,638,0,10,ALTA,26.400000,NO
13,TOPIRAMATO STADA 100 mg COMPRIMIDOS RECUBIERTO...,TOPIRAMATO,Laboratorio Stada S.L.,Laboratorio Stada S.L.,100.0,COMPRIMIDO,2007-03-13 23:00:00,2007-03-13 23:00:00,VÍA ORAL,1,1,1,1,1688,3,14,ALTA,36.620000,NO
14,TOPIRAMATO STADA 200 mg COMPRIMIDOS RECUBIERTO...,TOPIRAMATO,Laboratorio Stada S.L.,Laboratorio Stada S.L.,200.0,COMPRIMIDO,2007-03-13 23:00:00,2007-03-13 23:00:00,VÍA ORAL,1,1,1,1,1688,3,14,ALTA,73.250000,NO

In [76]:
df.dtypes

nombre                                 str
pactivos                               str
labtitular                             str
labcomercializador                     str
dosis (mg)                         float64
forma_farmaceutica_simplificada        str
estado_aut                             str
estado_rev                             str
vias_administracion                    str
comercializado                       int64
generico                             int64
afecta_conduccion                    int64
num_principios_activos               int64
Volumen_Informativo                  int64
Complejidad_Desglose                 int64
Indicador_Riesgo                     int64
Estado                                 str
Precio venta al público con IVA    float64
Tratamiento de larga duración          str
dtype: object

In [77]:
df["estado_aut"] = pd.to_datetime(df["estado_aut"])
df["estado_rev"] = pd.to_datetime(df["estado_rev"])
print(df.dtypes)

nombre                                        str
pactivos                                      str
labtitular                                    str
labcomercializador                            str
dosis (mg)                                float64
forma_farmaceutica_simplificada               str
estado_aut                         datetime64[us]
estado_rev                         datetime64[us]
vias_administracion                           str
comercializado                              int64
generico                                    int64
afecta_conduccion                           int64
num_principios_activos                      int64
Volumen_Informativo                         int64
Complejidad_Desglose                        int64
Indicador_Riesgo                            int64
Estado                                        str
Precio venta al público con IVA           float64
Tratamiento de larga duración                 str
dtype: object

In [78]:
df["aut_day"] = df["estado_aut"].dt.day
df["aut_month"] = df["estado_aut"].dt.month
df["aut_year"] = df["estado_aut"].dt.year

df["rev_day"] = df["estado_rev"].dt.day
df["rev_month"] = df["estado_rev"].dt.month
df["rev_year"] = df["estado_rev"].dt.year

df.drop(["estado_aut", "estado_rev"], axis=1, inplace=True)
df.dtypes

nombre                                 str
pactivos                               str
labtitular                             str
labcomercializador                     str
dosis (mg)                         float64
forma_farmaceutica_simplificada        str
vias_administracion                    str
comercializado                       int64
generico                             int64
afecta_conduccion                    int64
num_principios_activos               int64
Volumen_Informativo                  int64
Complejidad_Desglose                 int64
Indicador_Riesgo                     int64
Estado                                 str
Precio venta al público con IVA    float64
Tratamiento de larga duración          str
aut_day                              int32
aut_month                            int32
aut_year                             int32
rev_day                              int32
rev_month                            int32
rev_year                             int32
dtype: object

In [79]:
names = df["nombre"].values
print(names.shape)

(70,)

In [80]:
df.drop("nombre", inplace=True, axis=1)

In [81]:
text_columns = df.select_dtypes(include=['str']).columns
print(text_columns)

Index(['pactivos', 'labtitular', 'labcomercializador',
       'forma_farmaceutica_simplificada', 'vias_administracion', 'Estado',
       'Tratamiento de larga duración'],
      dtype='str')

In [89]:
encoder = preprocessing.OneHotEncoder(handle_unknown='error', min_frequency=0.7)
encoded_data = encoder.fit_transform(df[text_columns])

encoded_df = pd.DataFrame(
    encoded_data.toarray(),
    columns=encoder.get_feature_names_out(text_columns)
)

final_df = pd.concat(
    [df.drop(columns=text_columns), encoded_df],
    axis=1
)
final_df.head()

,dosis (mg),comercializado,generico,afecta_conduccion,num_principios_activos,Volumen_Informativo,Complejidad_Desglose,Indicador_Riesgo,Precio venta al público con IVA,aut_day,...,labtitular_infrequent_sklearn,labcomercializador_infrequent_sklearn,forma_farmaceutica_simplificada_COMPRIMIDO,forma_farmaceutica_simplificada_infrequent_sklearn,vias_administracion_VÍA ORAL,vias_administracion_infrequent_sklearn,Estado_ALTA,Estado_infrequent_sklearn,Tratamiento de larga duración_NO,Tratamiento de larga duración_infrequent_sklearn
0,12.5,1,1,1,1,636,1,14,32.085076,16,...,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1,12.5,1,1,1,1,662,1,13,19.530000,18,...,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
2,12.5,1,1,1,1,650,1,13,19.530000,26,...,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
3,600.0,1,1,0,1,1375,0,12,2.500000,29,...,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0
4,600.0,1,1,0,1,1238,0,13,1.970000,10,...,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0

In [87]:
X = df.to_numpy()
print(X.shape)

(70, 22)